import os
import io
import zipfile
import uuid
from typing import BinaryIO
from models.curriculum import CourseAST

class ScormService:
    @staticmethod
    def _generate_imsmanifest(ast: CourseAST) -> str:
        """
        Generates a SCORM 1.2 compliant imsmanifest.xml from the AST.
        """
        org_id = f"ORG_{uuid.uuid4().hex}"
        
        items_xml = ""
        resources_xml = ""
        
        for i, module in enumerate(ast.modules):
            mod_item_id = f"ITEM_MOD_{module.id}"
            items_xml += f'      <item identifier="{mod_item_id}" isvisible="true">\n'
            items_xml += f'        <title>{module.title}</title>\n'
            
            for j, lesson in enumerate(module.lessons):
                les_item_id = f"ITEM_LES_{lesson.id}"
                res_id = f"RES_{lesson.id}"
                html_filename = f"{lesson.id}.html"
                
                items_xml += f'        <item identifier="{les_item_id}" identifierref="{res_id}">\n'
                items_xml += f'          <title>{lesson.title}</title>\n'
                items_xml += f'        </item>\n'
                
                resources_xml += f'    <resource identifier="{res_id}" type="webcontent" adlcp:scormtype="sco" href="{html_filename}">\n'
                resources_xml += f'      <file href="{html_filename}"/>\n'
                resources_xml += f'    </resource>\n'
                
            items_xml += f'      </item>\n'
            
        manifest = f"""<?xml version="1.0" standalone="no" ?>
<manifest identifier="MANIFEST_{uuid.uuid4().hex}" version="1"
          xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
          xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                              http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
                              http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>
  <organizations default="{org_id}">
    <organization identifier="{org_id}">
      <title>{ast.title}</title>
{items_xml}
    </organization>
  </organizations>
  <resources>
{resources_xml}
  </resources>
</manifest>"""
        return manifest

    @staticmethod
    def _generate_lesson_html(lesson) -> str:
        """
        Generates a basic HTML file for a lesson including SCORM initialization logic.
        """
        lo_html = ""
        for lo in lesson.learning_objectives:
            lo_html += f"""
            <div style="margin-bottom: 20px; padding: 15px; border: 1px solid #ccc; border-radius: 8px;">
                <h4>{lo.text}</h4>
                <div style="font-size: 12px; color: #666; font-family: monospace;">
                    <span>Bloom Verb: <strong>{lo.bloom_verb.value}</strong></span> |
                    <span>Level: <strong>{lo.bloom_level.value}</strong></span>
                </div>
                <div style="margin-top: 10px; font-size: 14px; font-style: italic; background: #f9f9f9; padding: 10px; border-left: 3px solid #123d2d;">
                    "{lo.source_spans[0] if lo.source_spans else 'No grounded source provided.'}"
                </div>
            </div>
            """
            
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>{lesson.title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #333; }}
        h1 {{ color: #123d2d; }}
        h3 {{ color: #555; margin-top: 40px; border-bottom: 1px solid #eee; padding-bottom: 10px; }}
    </style>
    <script>
        // Minimal SCORM 1.2 Runtime Stub (In a real product, use pipwerks SCORM wrapper)
        var API = null;
        function findAPI(win) {{
            while (win.API == null && win.parent != null && win.parent != win) {{
                win = win.parent;
            }}
            return win.API;
        }}
        window.onload = function() {{
            API = findAPI(window);
            if (API != null) {{
                API.LMSInitialize("");
                API.LMSSetValue("cmi.core.lesson_status", "completed");
                API.LMSCommit("");
            }}
        }};
        window.onunload = function() {{
            if (API != null) {{
                API.LMSFinish("");
            }}
        }};
    </script>
</head>
<body>
    <h1>{lesson.title}</h1>
    <p>Welcome to this lesson. Please review the learning objectives below:</p>
    
    <h3>Learning Objectives</h3>
    {lo_html}
    
    <div style="margin-top: 50px; text-align: center; color: #999; font-size: 12px;">
        Generated by Darwinity AI Course Builder
    </div>
</body>
</html>"""
        return html

    @staticmethod
    def generate_scorm_package(ast: CourseAST) -> io.BytesIO:
        """
        Packages the AST into a fully compliant SCORM 1.2 zip file.
        Returns the zip file as a BytesIO buffer.
        """
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
            # 1. Add the imsmanifest.xml
            manifest_xml = ScormService._generate_imsmanifest(ast)
            zip_file.writestr("imsmanifest.xml", manifest_xml)
            
            # 2. Add empty XSD files (SCORM standard requires these in the root for some strict LMSs, 
            # but many LMSs ignore them if missing. We will skip them for the hackathon MVP or add dummies if strictly needed. 
            # For Canvas, the xml is usually enough to pass).
            
            # 3. Add the actual HTML content files
            for module in ast.modules:
                for lesson in module.lessons:
                    html_content = ScormService._generate_lesson_html(lesson)
                    filename = f"{lesson.id}.html"
                    zip_file.writestr(filename, html_content)
                    
        zip_buffer.seek(0)
        return zip_buffer
