import { useDarwinity } from "@/contexts/DarwinityStoreContext";
import { BookOpen, CalendarDays, CheckCircle2, ClipboardCheck, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Plan = { pace: "light" | "balanced" | "intensive"; examDate: string; diagnostics: Record<string, number>; assignments: { id: string; title: string; due: string; done: boolean }[] };
const KEY = "learnloop-learning-plan-v1";
const blank: Plan = { pace: "balanced", examDate: "", diagnostics: {}, assignments: [] };

export default function LearningControlCenter() {
  const { state } = useDarwinity();
  const [plan, setPlan] = useState<Plan>(blank);
  const [assignment, setAssignment] = useState("");
  const [due, setDue] = useState("");
  useEffect(() => { try { const value = JSON.parse(localStorage.getItem(KEY) || "null"); if (value) setPlan({ ...blank, ...value }); } catch { /* start fresh */ } }, []);
  useEffect(() => { localStorage.setItem(KEY, JSON.stringify(plan)); }, [plan]);
  const courses = state.courses;
  const dueReviews = useMemo(() => courses.flatMap(c => (c.lessons || []).filter(l => !c.mastery?.completedLessonIds?.includes(l.id)).slice(0, 2).map(l => ({ course: c.title, lesson: l.title }))), [courses]);
  const addAssignment = () => { if (!assignment.trim()) return; setPlan(p => ({ ...p, assignments: [...p.assignments, { id: String(Date.now()), title: assignment.trim(), due, done: false }] })); setAssignment(""); setDue(""); };
  return <div className="max-w-6xl mx-auto py-10 px-6 space-y-8">
    <div><p className="text-xs font-bold tracking-widest uppercase text-emerald-700">Learning intelligence</p><h1 className="text-4xl font-extrabold tracking-tight mt-2">Your adaptive study plan</h1><p className="text-gray-500 mt-2">A persistent layer over your existing courses—nothing here replaces your material.</p></div>
    <div className="grid lg:grid-cols-3 gap-5"><section className="lg:col-span-2 rounded-2xl border bg-white p-6"><div className="flex items-center gap-2 font-extrabold"><ClipboardCheck className="text-emerald-600" /> Daily review queue</div><p className="text-sm text-gray-500 mt-1">Prioritised from incomplete lessons and weak concepts.</p><div className="mt-4 space-y-2">{dueReviews.length ? dueReviews.map(item => <div key={`${item.course}-${item.lesson}`} className="flex items-center justify-between rounded-xl bg-gray-50 p-3"><span><b>{item.lesson}</b><small className="block text-gray-500">{item.course}</small></span><span className="text-xs font-bold text-amber-700">Due today</span></div>) : <p className="text-sm text-gray-500">You’re caught up. Complete a lesson to build a review queue.</p>}</div></section><section className="rounded-2xl border bg-[#123d2d] text-white p-6"><Sparkles className="text-emerald-200" /><h2 className="font-extrabold text-xl mt-3">Pace adjustment</h2><p className="text-sm text-emerald-100 mt-2">Choose how aggressively the next lessons and reviews are scheduled.</p><select value={plan.pace} onChange={e => setPlan(p => ({ ...p, pace: e.target.value as Plan["pace"] }))} className="mt-4 w-full rounded-xl bg-white text-gray-900 p-2 text-sm font-bold"><option value="light">Light</option><option value="balanced">Balanced</option><option value="intensive">Intensive</option></select></section></div>
    <div className="grid lg:grid-cols-2 gap-5"><section className="rounded-2xl border bg-white p-6"><h2 className="font-extrabold flex gap-2"><CalendarDays className="text-violet-600" /> Assignments & deadlines</h2><div className="mt-4 flex gap-2"><input value={assignment} onChange={e => setAssignment(e.target.value)} className="min-w-0 flex-1 border rounded-xl px-3" placeholder="Assignment title" /><input type="date" value={due} onChange={e => setDue(e.target.value)} className="border rounded-xl px-2" /><button onClick={addAssignment} className="rounded-xl bg-[#123d2d] text-white px-3 font-bold">Add</button></div><div className="mt-4 space-y-2">{plan.assignments.map(a => <label key={a.id} className="flex gap-3 rounded-xl bg-gray-50 p-3 text-sm"><input type="checkbox" checked={a.done} onChange={() => setPlan(p => ({ ...p, assignments: p.assignments.map(x => x.id === a.id ? { ...x, done: !x.done } : x) }))} /><span className={a.done ? "line-through text-gray-400" : ""}>{a.title}<small className="block text-gray-500">{a.due || "No deadline"}</small></span></label>)}</div></section><section className="rounded-2xl border bg-white p-6"><h2 className="font-extrabold flex gap-2"><BookOpen className="text-blue-600" /> Grounding & trust</h2><p className="text-sm text-gray-500 mt-2">Course objectives already retain source spans. Generated content should cite its source, distinguish general knowledge, and never silently overwrite your work.</p><div className="mt-4 space-y-2 text-sm"><p className="flex gap-2"><CheckCircle2 className="text-emerald-600" size={18} /> Source-linked course objectives</p><p className="flex gap-2"><CheckCircle2 className="text-emerald-600" size={18} /> Versioned course generation & SCORM export</p><p className="flex gap-2"><ShieldCheck className="text-emerald-600" size={18} /> Confirm destructive changes; preserve originals</p></div></section></div>
  </div>;
}
